"""empty message

Revision ID: 4830d815dd97
Revises: 1a5eb02403bc
Create Date: 2024-10-01 20:24:33.412657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4830d815dd97'
down_revision = '1a5eb02403bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
