"""empty message

Revision ID: 89da0eb090e5
Revises: 92a74ae5a507
Create Date: 2024-10-02 22:19:59.268168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89da0eb090e5'
down_revision = '92a74ae5a507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])
        batch_op.drop_column('character_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorite_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorite_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('planet')
        batch_op.drop_column('character')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
