"""empty message

Revision ID: a2ef9a884ff8
Revises: c34d0e0767bd
Create Date: 2024-10-02 23:09:13.588502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ef9a884ff8'
down_revision = 'c34d0e0767bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_character_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])
        batch_op.drop_column('character')
        batch_op.drop_column('planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planet_fkey', 'planet', ['planet'], ['id'])
        batch_op.create_foreign_key('favorite_character_fkey', 'character', ['character'], ['id'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
